name: Docker Image CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  writeData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: ./src/apps/IDEAL/input.csv
          columns: file, type, junit
          "file": myfile.java
          "type": java
          "junit": junit
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t ideal
      - name: Run the Docker image
        run: docker run -v ./:/app/ -t ideal
        
